### ISSUE TITLE
苹果端或者PC端有办法吗，或者linux端服务器实现打卡有思路，同学

### ISSUE THREAD

**Issue by ly5519** [JiyeHoo/Auto-Daily-Clock#1]
（看了看一眼自己的苹果手机）（猫猫头流泪）

**Comment by JiyeHoo** [comment]
1. iOS 的快捷之类，类似 AutoJS，而且功能更强大；
2. Android 虚拟机跑 AutoJS；
3. Android Hook 钉钉，抓到启动页面，获取启动参数（类似 WebView 的），自己调用；
4. 上一步的基础上进阶，加载一个 JS 自动提交；
5. 直接抓 Post 包，修改 token 等参数，直接在任何操作系统上发包，实现打卡
